/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AdorableAvatar {
        "name": string;
        "rounded": boolean;
        "size": number;
        "src": string;
    }
}
declare global {
    interface HTMLAdorableAvatarElement extends Components.AdorableAvatar, HTMLStencilElement {
    }
    var HTMLAdorableAvatarElement: {
        prototype: HTMLAdorableAvatarElement;
        new (): HTMLAdorableAvatarElement;
    };
    interface HTMLElementTagNameMap {
        "adorable-avatar": HTMLAdorableAvatarElement;
    }
}
declare namespace LocalJSX {
    interface AdorableAvatar {
        "name"?: string;
        "rounded"?: boolean;
        "size"?: number;
        "src"?: string;
    }
    interface IntrinsicElements {
        "adorable-avatar": AdorableAvatar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "adorable-avatar": LocalJSX.AdorableAvatar & JSXBase.HTMLAttributes<HTMLAdorableAvatarElement>;
        }
    }
}
